### ISSUE TITLE
Fish Tank switch has generic name.

### ISSUE THREAD

**Issue by PurelyNicole** [PurelyNicole/Home-AssistantConfig#1]
The fish tank switch is named "mqtt_switch." This needs to be name that is identifiable.

**Comment by ezeckner** [comment]
the issue with making this change is it requires the hardware by the fish tank to be uninstalled and moved upstairs and reprogrammed.

**Comment by PurelyNicole** [comment]
You are/were blending the two [Configuration Styles](https://home-assistant.io/docs/configuration/devices/) for your [MQTT switch](https://github.com/PurelyNicole/Home-AssistantConfig/blob/9caeb3eb0bbebf7c65ab4ed0ebb953cd49ef4421/switches.yaml.bak#L2). When I removed the "mqtt" the switch entity was renamed to switch.switch1 instead of "mqtt switch." This is why the entity no long shows on the HADBoard. 

I think once we go to naming these in style 1, we can give it a meaningful name in Home Assistant, while MQTT still sees it as "switch1."
